# fly.toml app configuration file generated for express-mini-message-board on 2023-10-02T10:42:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "express-mini-message-board"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
